name: Publish

on:
  workflow_dispatch:
    inputs:
      semver:
        description: 'Semver bump type'
        required: true

jobs:
  publish-to-npm:
    environment: npm
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_REPO_TOKEN }}

      - name: Setup Node and pnpm
        uses: silverhand-io/actions-node-pnpm-run-steps@v1.0.3

      - name: Configure Git user
        run: |
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions

      - name: Publish to NPM
        # add `no-verify-access` due to https://github.com/lerna/lerna/issues/2788
        run: |
          pnpm -- lerna publish -m "release: %s" --conventional-commits --preid=rc --no-verify-access --create-release=github --yes ${{ github.event.inputs.semver }}
        env:
          GH_TOKEN: ${{ secrets.GH_REPO_TOKEN }}

      - name: Update pnpm lockfile
        run: pnpm i --frozen-lockfile=false --offline

      - name: Commit and push lockfile changes
        continue-on-error: true
        run: |
          git commit -am'chore: update lockfile'
          git push
